export const DOG_BREEDS = [
  "Australian Shepherd",
  "Basset Hound",
  "Beagle",
  "Belgian Malinois",
  "Bernese Mountain Dog",
  "Border Collie",
  "Boston Terrier",
  "Boxer",
  "Bulldog",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Cocker Spaniel",
  "Collie",
  "Dachshund",
  "Doberman Pinscher",
  "English Springer Spaniel",
  "French Bulldog",
  "German Shepherd",
  "German Shorthaired Pointer",
  "Golden Retriever",
  "Great Dane",
  "Havanese",
  "Hungarian Vizsla",
  "Labrador Retriever",
  "Maltese",
  "Mastiff",
  "Miniature Schnauzer",
  "Pembroke Welsh Corgi",
  "Pomeranian",
  "Poodle",
  "Pug",
  "Rottweiler",
  "Shetland Sheepdog",
  "Shih Tzu",
  "Siberian Husky",
  "Staffordshire Bull Terrier",
  "Whippet",
  "Yorkshire Terrier",
  "Mixed Breed",
  "Other",
] as const;
