export const DOG_BREEDS = [
  "Labrador Retriever",
  "Golden Retriever",
  "German Shepherd",
  "Boxer",
  "German Shorthaired Pointer",
  "English Springer Spaniel",
  "Australian Shepherd",
  "Border Collie",
  "Siberian Husky",
  "Hungarian Vizsla",
  "Belgian Malinois",
  "Collie",

  "Rottweiler",
  "Cane Corso",
  "Doberman Pinscher",
  "Staffordshire Bull Terrier",
  "Great Dane",
  "Mastiff",

  "Cocker Spaniel",
  "Beagle",
  "Bulldog",
  "Basset Hound",
  "Bernese Mountain Dog",

  "French Bulldog",
  "Dachshund",
  "Cavalier King Charles Spaniel",
  "Pembroke Welsh Corgi",
  "Miniature Schnauzer",
  "Boston Terrier",
  "Shih Tzu",
  "Chihuahua",
  "Pug",

  "Poodle",
  "Yorkshire Terrier",
  "Pomeranian",
  "Havanese",
  "Shetland Sheepdog",
  "Maltese",
  "Whippet",

  "Mixed Breed",
  "Other",
] as const;
